title: Martín Volpe
description: Personal website of Martín Volpe - Developer, Creator, Builder
url: "https://martinvol.pe"
baseurl: ""

# Build settings
permalink: pretty
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-contentblocks

include:
  - dist

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - src/input.css
  - README.md
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: "redirects.json"
    values:
      sitemap: false
