title: Martín Volpe
description: Personal website of Martín Volpe - Developer, Creator, Builder
url: "https://martinvol.pe"
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap

include:
  - dist

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - src
  - README.md
  - Gemfile
  - Gemfile.lock
